# Generated by Django 3.2.8 on 2021-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentCode',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
