# Generated by Django 3.2.8 on 2021-12-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='resourceUrl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='resourceLink',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
