# Generated by Django 3.2.8 on 2021-12-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0003_auto_20211212_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='stack',
            new_name='stackNote',
        ),
    ]
