# Generated by Django 3.2.8 on 2021-12-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0004_rename_stack_note_stacknote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='stackNote',
            new_name='stack',
        ),
    ]
