# Generated by Django 3.2.8 on 2021-12-12 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0005_rename_stacknote_note_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='note',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='notesApp.note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploadName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
